server:
  port: 1000

spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
      format_sql: true
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/tejas
    username: postgres
    password: 2810
